package cn.edu.bzu.zw.mytally.model;

import cn.edu.bzu.zw.mytally.model.base.BaseTally;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tally extends BaseTally<Tally> {
	public static final Tally dao = new Tally().dao();
}
