package cn.edu.bzu.zw.mytally.model;

import cn.edu.bzu.zw.mytally.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
}
