package cn.edu.bzu.zw.mytally.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTally<M extends BaseTally<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}

	public java.lang.Integer getUserid() {
		return get("userid");
	}

	public M setDirection(java.lang.Integer direction) {
		set("direction", direction);
		return (M)this;
	}

	public java.lang.Integer getDirection() {
		return get("direction");
	}

	public M setAmount(java.lang.Integer amount) {
		set("amount", amount);
		return (M)this;
	}

	public java.lang.Integer getAmount() {
		return get("amount");
	}

	public M setNote(java.lang.String note) {
		set("note", note);
		return (M)this;
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public M setTallytime(java.util.Date tallytime) {
		set("tallytime", tallytime);
		return (M)this;
	}

	public java.util.Date getTallytime() {
		return get("tallytime");
	}

}
